<?php

namespace Database\Seeders;

use App\Models\InventoryItem;
use Illuminate\Database\Seeder;

class InventoryItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'title' => 'MacBook Pro 16" M3 Pro',
                'description' => 'Apple MacBook Pro 16-inch, M3 Pro chip, 18GB RAM, 512GB SSD, Space Black',
                'category' => 'Laptop',
                'price' => 2499.00,
                'currency' => 'EUR',
                'serial_number' => 'C02ZN1MDLVDL',
                'model_number' => 'MRW13LL/A',
                'status' => 'in_use',
            ],
            [
                'title' => 'MacBook Air 13" M3',
                'description' => 'Apple MacBook Air 13-inch, M3 chip, 16GB RAM, 256GB SSD, Midnight',
                'category' => 'Laptop',
                'price' => 1199.00,
                'currency' => 'EUR',
                'serial_number' => 'C02YK2NDLVDM',
                'model_number' => 'MRXN3LL/A',
                'status' => 'available',
            ],
            [
                'title' => 'Lenovo ThinkPad X1 Carbon Gen 12',
                'description' => 'Intel Core Ultra 7, 32GB RAM, 1TB SSD, 14" 2.8K OLED display',
                'category' => 'Laptop',
                'price' => 1849.00,
                'currency' => 'EUR',
                'serial_number' => 'PF4DCNX8',
                'model_number' => '21KC004RUS',
                'status' => 'in_use',
            ],
            [
                'title' => 'Dell Latitude 5550',
                'description' => 'Intel Core i7-1365U, 16GB RAM, 512GB SSD, 15.6" FHD',
                'category' => 'Laptop',
                'price' => 1299.00,
                'currency' => 'EUR',
                'serial_number' => '7VSG3K3',
                'model_number' => 'LAT5550-I7',
                'status' => 'in_use',
            ],
            [
                'title' => 'Dell OptiPlex 7020 Tower',
                'description' => 'Intel Core i7-14700, 32GB DDR5, 512GB NVMe SSD, Windows 11 Pro',
                'category' => 'Desktop',
                'price' => 1149.00,
                'currency' => 'EUR',
                'serial_number' => 'D4XG7N2',
                'model_number' => 'OPT7020-TWR',
                'status' => 'in_use',
            ],
            [
                'title' => 'HP EliteDesk 800 G9 Mini',
                'description' => 'Intel Core i5-13500T, 16GB DDR5, 256GB SSD, Wi-Fi 6E',
                'category' => 'Desktop',
                'price' => 799.00,
                'currency' => 'EUR',
                'serial_number' => '5CG4231BRN',
                'model_number' => 'ED800G9-MINI',
                'status' => 'available',
            ],
            [
                'title' => 'Dell UltraSharp U2723QE 27"',
                'description' => '27" 4K UHD IPS Black, USB-C Hub, HDR 400, 98% DCI-P3',
                'category' => 'Monitor',
                'price' => 579.00,
                'currency' => 'EUR',
                'serial_number' => 'CN0DK9F1FCC',
                'model_number' => 'U2723QE',
                'status' => 'in_use',
            ],
            [
                'title' => 'Samsung Odyssey G7 32"',
                'description' => '32" QHD 240Hz curved gaming monitor, 1ms response, HDR600',
                'category' => 'Monitor',
                'price' => 649.00,
                'currency' => 'EUR',
                'serial_number' => 'H4ZT900123',
                'model_number' => 'LS32BG702',
                'status' => 'available',
            ],
            [
                'title' => 'LG 34WN80C-B 34" UltraWide',
                'description' => '34" WQHD IPS UltraWide, USB-C 60W PD, HDR10, sRGB 99%',
                'category' => 'Monitor',
                'price' => 499.00,
                'currency' => 'EUR',
                'serial_number' => '402NTGA8P901',
                'model_number' => '34WN80C-B',
                'status' => 'in_use',
            ],
            [
                'title' => 'Logitech MX Keys S',
                'description' => 'Advanced wireless illuminated keyboard, Bluetooth/USB, backlit, multi-device',
                'category' => 'Keyboard',
                'price' => 109.00,
                'currency' => 'EUR',
                'serial_number' => '2337FC01A234',
                'model_number' => '920-011406',
                'status' => 'in_use',
            ],
            [
                'title' => 'Logitech MX Keys S',
                'description' => 'Advanced wireless illuminated keyboard, Bluetooth/USB, backlit, multi-device',
                'category' => 'Keyboard',
                'price' => 109.00,
                'currency' => 'EUR',
                'serial_number' => '2337FC01A235',
                'model_number' => '920-011406',
                'status' => 'available',
            ],
            [
                'title' => 'Apple Magic Keyboard with Touch ID',
                'description' => 'Wireless keyboard with numeric keypad, Touch ID, USB-C, silver',
                'category' => 'Keyboard',
                'price' => 199.00,
                'currency' => 'EUR',
                'serial_number' => 'FVF0P1GRJK78',
                'model_number' => 'MK2C3LL/A',
                'status' => 'in_use',
            ],
            [
                'title' => 'Logitech MX Master 3S',
                'description' => 'Wireless performance mouse, 8K DPI, quiet clicks, Bluetooth/USB, ergonomic',
                'category' => 'Mouse',
                'price' => 99.00,
                'currency' => 'EUR',
                'serial_number' => '2249FE03B567',
                'model_number' => '910-006556',
                'status' => 'in_use',
            ],
            [
                'title' => 'Logitech MX Master 3S',
                'description' => 'Wireless performance mouse, 8K DPI, quiet clicks, Bluetooth/USB, ergonomic',
                'category' => 'Mouse',
                'price' => 99.00,
                'currency' => 'EUR',
                'serial_number' => '2249FE03B568',
                'model_number' => '910-006556',
                'status' => 'in_use',
            ],
            [
                'title' => 'Apple Magic Mouse USB-C',
                'description' => 'Multi-touch surface, USB-C charging, white',
                'category' => 'Mouse',
                'price' => 85.00,
                'currency' => 'EUR',
                'serial_number' => 'CC2Y41KQJCL5',
                'model_number' => 'MK2C3ZM/A',
                'status' => 'available',
            ],
            [
                'title' => 'Jabra Evolve2 85',
                'description' => 'Wireless stereo ANC headset, Bluetooth 5.2, 37h battery, MS Teams certified',
                'category' => 'Headset',
                'price' => 349.00,
                'currency' => 'EUR',
                'serial_number' => '70E40AF8B012',
                'model_number' => '28599-999-999',
                'status' => 'in_use',
            ],
            [
                'title' => 'Poly Voyager Focus 2',
                'description' => 'Wireless ANC stereo headset, Bluetooth, USB-A, 19h battery, Teams certified',
                'category' => 'Headset',
                'price' => 249.00,
                'currency' => 'EUR',
                'serial_number' => 'PLY20230456',
                'model_number' => '213727-01',
                'status' => 'in_use',
            ],
            [
                'title' => 'Apple AirPods Pro 2nd Gen',
                'description' => 'Active noise cancellation, USB-C MagSafe case, adaptive audio',
                'category' => 'Headset',
                'price' => 249.00,
                'currency' => 'EUR',
                'serial_number' => 'G0TVN4F0MX',
                'model_number' => 'MTJV3ZM/A',
                'status' => 'available',
            ],
            [
                'title' => 'iPhone 15 Pro 256GB',
                'description' => 'Apple iPhone 15 Pro, A17 Pro chip, 256GB, Natural Titanium, corporate line',
                'category' => 'Phone',
                'price' => 1199.00,
                'currency' => 'EUR',
                'serial_number' => 'F17DQ8A0PH',
                'model_number' => 'MTV53LL/A',
                'status' => 'in_use',
            ],
            [
                'title' => 'Samsung Galaxy S24 Ultra 256GB',
                'description' => 'Samsung Galaxy S24 Ultra, Snapdragon 8 Gen 3, 256GB, Titanium Gray',
                'category' => 'Phone',
                'price' => 1329.00,
                'currency' => 'EUR',
                'serial_number' => 'R5CT41BGXLW',
                'model_number' => 'SM-S928BZTD',
                'status' => 'in_use',
            ],
            [
                'title' => 'iPad Pro 12.9" M2 256GB',
                'description' => 'Apple iPad Pro 12.9-inch, M2 chip, 256GB, Wi-Fi, Space Gray, with Apple Pencil',
                'category' => 'Tablet',
                'price' => 1199.00,
                'currency' => 'EUR',
                'serial_number' => 'DMPYG4F0Q1GC',
                'model_number' => 'MNXR3LL/A',
                'status' => 'in_use',
            ],
            [
                'title' => 'HP LaserJet Pro MFP 4101fdw',
                'description' => 'Monochrome all-in-one laser printer, duplex, fax, wireless, 40 ppm',
                'category' => 'Printer',
                'price' => 449.00,
                'currency' => 'EUR',
                'serial_number' => 'CNBKM5D1G2',
                'model_number' => '2Z619F',
                'status' => 'in_use',
            ],
            [
                'title' => 'HP Color LaserJet Pro MFP 4301fdw',
                'description' => 'Color laser all-in-one, 35 ppm, duplex, Wi-Fi Direct, ADF',
                'category' => 'Printer',
                'price' => 599.00,
                'currency' => 'EUR',
                'serial_number' => 'CNBKM7F3H8',
                'model_number' => '4RA82F',
                'status' => 'in_use',
            ],
            [
                'title' => 'Fujitsu ScanSnap iX1600',
                'description' => 'Wireless high-speed document scanner, 40 ppm, duplex, touchscreen, Wi-Fi',
                'category' => 'Scanner',
                'price' => 395.00,
                'currency' => 'EUR',
                'serial_number' => 'FJSC2301K456',
                'model_number' => 'PA03770-B615',
                'status' => 'in_use',
            ],
            [
                'title' => 'Ubiquiti UniFi Dream Machine Pro',
                'description' => 'All-in-one network appliance: router, switch, security gateway, NVR',
                'category' => 'Network Equipment',
                'price' => 379.00,
                'currency' => 'EUR',
                'serial_number' => 'F09FC2EA4C30',
                'model_number' => 'UDM-PRO',
                'status' => 'in_use',
            ],
            [
                'title' => 'Ubiquiti UniFi Switch 24 PoE',
                'description' => '24-port managed Gigabit PoE switch, 2x SFP+, 95W PoE budget',
                'category' => 'Network Equipment',
                'price' => 399.00,
                'currency' => 'EUR',
                'serial_number' => 'F09FC2EB7D41',
                'model_number' => 'USW-24-POE',
                'status' => 'in_use',
            ],
            [
                'title' => 'Ubiquiti UniFi AP U6 Pro',
                'description' => 'Wi-Fi 6 access point, 5.3 Gbps, PoE powered, ceiling mount',
                'category' => 'Network Equipment',
                'price' => 149.00,
                'currency' => 'EUR',
                'serial_number' => 'F09FC2EC9A52',
                'model_number' => 'U6-PRO',
                'status' => 'in_use',
            ],
            [
                'title' => 'Ubiquiti UniFi AP U6 Pro',
                'description' => 'Wi-Fi 6 access point, 5.3 Gbps, PoE powered, ceiling mount',
                'category' => 'Network Equipment',
                'price' => 149.00,
                'currency' => 'EUR',
                'serial_number' => 'F09FC2EC9A53',
                'model_number' => 'U6-PRO',
                'status' => 'available',
            ],
            [
                'title' => 'Herman Miller Aeron Chair Size B',
                'description' => 'Ergonomic office chair, graphite frame, PostureFit SL, fully adjustable arms',
                'category' => 'Furniture',
                'price' => 1395.00,
                'currency' => 'EUR',
                'serial_number' => 'HM-AER-2024-0012',
                'model_number' => 'AER1B23DWALPVPRSNASNASG1',
                'status' => 'in_use',
            ],
            [
                'title' => 'Herman Miller Aeron Chair Size B',
                'description' => 'Ergonomic office chair, graphite frame, PostureFit SL, fully adjustable arms',
                'category' => 'Furniture',
                'price' => 1395.00,
                'currency' => 'EUR',
                'serial_number' => 'HM-AER-2024-0013',
                'model_number' => 'AER1B23DWALPVPRSNASNASG1',
                'status' => 'in_use',
            ],
            [
                'title' => 'Flexispot E7 Standing Desk 160x80',
                'description' => 'Electric sit-stand desk, dual motor, 160x80cm bamboo top, memory presets',
                'category' => 'Furniture',
                'price' => 549.00,
                'currency' => 'EUR',
                'serial_number' => 'FS-E7-2024-0034',
                'model_number' => 'E7-BBN-160',
                'status' => 'in_use',
            ],
            [
                'title' => 'Flexispot E7 Standing Desk 160x80',
                'description' => 'Electric sit-stand desk, dual motor, 160x80cm bamboo top, memory presets',
                'category' => 'Furniture',
                'price' => 549.00,
                'currency' => 'EUR',
                'serial_number' => 'FS-E7-2024-0035',
                'model_number' => 'E7-BBN-160',
                'status' => 'available',
            ],
            [
                'title' => 'Whiteboard 120x90cm Magnetic',
                'description' => 'Wall-mounted magnetic dry-erase whiteboard, aluminum frame, marker tray',
                'category' => 'Office Supplies',
                'price' => 89.00,
                'currency' => 'EUR',
                'serial_number' => null,
                'model_number' => 'WB-MAG-12090',
                'status' => 'in_use',
            ],
            [
                'title' => 'Logitech Spotlight Presentation Remote',
                'description' => 'Advanced wireless presenter, digital highlighting, 30m range, USB-C',
                'category' => 'Office Supplies',
                'price' => 119.00,
                'currency' => 'EUR',
                'serial_number' => '2148SP04C789',
                'model_number' => '910-005166',
                'status' => 'available',
            ],
            [
                'title' => 'Dell Laptop Docking Station WD22TB4',
                'description' => 'Thunderbolt 4 dock, dual 4K@60Hz, 130W PD, 4x USB-A, 2x USB-C, Ethernet',
                'category' => 'Other',
                'price' => 299.00,
                'currency' => 'EUR',
                'serial_number' => '7VSG3K3-DOCK1',
                'model_number' => 'WD22TB4',
                'status' => 'in_use',
            ],
            [
                'title' => 'CalDigit TS4 Thunderbolt 4 Dock',
                'description' => '18 ports, 98W PD, 2.5GbE, SD/microSD, 3x Thunderbolt 4 downstream',
                'category' => 'Other',
                'price' => 349.00,
                'currency' => 'EUR',
                'serial_number' => 'CDG-TS4-2024-001',
                'model_number' => 'TS4-US',
                'status' => 'in_use',
            ],
            [
                'title' => 'Logitech Rally Bar Mini',
                'description' => 'All-in-one video conference bar, 4K camera, AI auto-framing, beamforming mics',
                'category' => 'Other',
                'price' => 2999.00,
                'currency' => 'EUR',
                'serial_number' => '2367RB07D321',
                'model_number' => '960-001339',
                'status' => 'in_use',
            ],
            [
                'title' => 'APC Back-UPS Pro 1500VA',
                'description' => 'Uninterruptible power supply, 1500VA/900W, LCD, 10 outlets, USB',
                'category' => 'Other',
                'price' => 229.00,
                'currency' => 'EUR',
                'serial_number' => '3B2409X12345',
                'model_number' => 'BR1500G',
                'status' => 'in_use',
            ],
            [
                'title' => 'Samsung 870 EVO 1TB SSD (spare)',
                'description' => '2.5" SATA III SSD, 560MB/s read, spare for replacements',
                'category' => 'Other',
                'price' => 89.00,
                'currency' => 'EUR',
                'serial_number' => 'S6P3NJ0W401234A',
                'model_number' => 'MZ-77E1T0B/AM',
                'status' => 'available',
            ],
            [
                'title' => 'Dell P2422H 24" Monitor (damaged)',
                'description' => '24" FHD IPS, USB-C, dead pixels on right side — awaiting disposal',
                'category' => 'Monitor',
                'price' => 289.00,
                'currency' => 'EUR',
                'serial_number' => 'CN0DK5R2FCC',
                'model_number' => 'P2422H',
                'status' => 'damaged',
            ],
            [
                'title' => 'Lenovo ThinkPad T480',
                'description' => 'Intel Core i5-8350U, 8GB RAM, 256GB SSD — retired from service 2024',
                'category' => 'Laptop',
                'price' => 499.00,
                'currency' => 'EUR',
                'serial_number' => 'PF1A2B3C',
                'model_number' => '20L5000WUS',
                'status' => 'retired',
            ],
            [
                'title' => 'HP LaserJet Pro M404n (retired)',
                'description' => 'Monochrome laser printer, replaced by MFP 4101fdw — decommissioned',
                'category' => 'Printer',
                'price' => 249.00,
                'currency' => 'EUR',
                'serial_number' => 'CNBKL3C1D7',
                'model_number' => 'W1A52A',
                'status' => 'retired',
            ],
        ];

        foreach ($items as $data) {
            InventoryItem::firstOrCreate(
                ['serial_number' => $data['serial_number'] ?? $data['title']],
                $data
            );
        }
    }
}
